version: "3.9"

services:
  testament-ui-react:
    build:
      context: .
      dockerfile: Dockerfile
    image: testament-ui-react:latest
    container_name: testament-ui-react
    ports:
      - "7878:7878"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: testament-ui-react:latest
    container_name: testament-ui-react
    ports:
      - "7878:7878"
    restart: unless-stopped